CREATE DATABASE IF NOT EXISTS FLOODPATH;
USE FLOODPATH;

CREATE TABLE RIO (
    RIO_ID INT AUTO_INCREMENT PRIMARY KEY,
    NIVEL_AGUA DECIMAL(5,2),
    SENSOR_ID INT 
);

CREATE TABLE USUARIO (
    USUARIO_ID INT AUTO_INCREMENT PRIMARY KEY,
    LATITUDE DECIMAL(10, 8),
    LONGITUDE DECIMAL(11, 8)
);

CREATE TABLE SENSOR (
    SENSOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    STATUS VARCHAR(20),
    LONGITUDE DECIMAL(10, 8),
    LATITUDE DECIMAL(11, 8),
    ALERTAS TEXT,
    NIVEL_AGUA DECIMAL(5,2),
    RIO_ID INT,
    CONSTRAINT fk_sensor_rio FOREIGN KEY (RIO_ID) REFERENCES RIO(RIO_ID)
);

CREATE TABLE ROTA (
    ROTA_ID INT AUTO_INCREMENT PRIMARY KEY,
    NOME_ROTA VARCHAR(100) NULL,
    PONTO_PARTIDA_LAT DECIMAL(10, 8) NOT NULL,
    PONTO_PARTIDA_LNG DECIMAL(11, 8) NOT NULL,
    PONTO_DESTINO_LAT DECIMAL(10, 8) NOT NULL,
    PONTO_DESTINO_LNG DECIMAL(11, 8) NOT NULL,
    
    CONTADOR_FREQUENCIA INT DEFAULT 1, 
    DATA_CRIACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA_ULTIMA_UTILIZACAO TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    
    USUARIO_ID INT,
    CONSTRAINT fk_rota_usuario FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);

CREATE TABLE PONTOS_DA_ROTA (
    PONTO_ID INT AUTO_INCREMENT PRIMARY KEY,
    ROTA_ID INT NOT NULL,
    ORDEM INT NOT NULL, 
    LATITUDE DECIMAL(10, 8) NOT NULL,
    LONGITUDE DECIMAL(11, 8) NOT NULL,
    CONSTRAINT fk_pontos_rota FOREIGN KEY (ROTA_ID) REFERENCES ROTA(ROTA_ID) ON DELETE CASCADE
);

CREATE TABLE HISTORICO (
    HISTORICO_ID INT AUTO_INCREMENT PRIMARY KEY,
    DATA_HORA TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    NIVEL_AGUA DECIMAL(5,2),
    ESTA_INUNDADO BOOLEAN,
    SENSOR_ID INT,
    CONSTRAINT fk_historico_sensor FOREIGN KEY (SENSOR_ID) REFERENCES SENSOR(SENSOR_ID)
);

CREATE TABLE ALERTA (
    ALERTA_ID INT AUTO_INCREMENT PRIMARY KEY,
    DATA_HORA DATETIME,
    ATIVO BOOLEAN DEFAULT TRUE,
    NIVEL_GRAVIDADE ENUM('BAIXO', 'MEDIO', 'ALTO'),
    SENSOR_ID INT,
    CONSTRAINT fk_alerta_sensor FOREIGN KEY (SENSOR_ID) REFERENCES SENSOR(SENSOR_ID)
);

CREATE TABLE NAVEGACAO (
    NAVEGACAO_ID INT AUTO_INCREMENT PRIMARY KEY,
    LATITUDE DECIMAL(10, 8),
    LONGITUDE DECIMAL(11, 8),
    USUARIO_ID INT,
    CONSTRAINT fk_navegacao_usuario FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO(USUARIO_ID)
);

CREATE TABLE LOCAL (
    MAPA_ID INT AUTO_INCREMENT PRIMARY KEY,
    CEP VARCHAR(9),
    RUA VARCHAR(100),
    BAIRRO VARCHAR(50),
    NUMERO INT,
    AREAS_ALAGAVEIS BOOLEAN,
    SENSOR_ID INT,
    CONSTRAINT fk_local_sensor FOREIGN KEY (SENSOR_ID) REFERENCES SENSOR(SENSOR_ID)
);

CREATE TABLE LEITOR (
    LEITOR_ID INT AUTO_INCREMENT PRIMARY KEY,
    LEITURAS_TEMPO_REAL TIMESTAMP,
    SENSOR_ID INT,
    CONSTRAINT fk_leitor_sensor FOREIGN KEY (SENSOR_ID) REFERENCES SENSOR(SENSOR_ID)
);

